const taskList = document.querySelector("[data-js='task-list']");
const emptyTaskMessage = document.querySelector("[data-js='empty-task-message']");
const taskSearchInput = document.querySelector("[data-js='task-search-input']")
const taskFilterSelect = document.querySelector("[data-js='task-filter-select']");
const pendingCount = document.querySelector("[data-js='pending-count']");
const completedCount = document.querySelector("[data-js='completed-count']");
const clearAllBtn = document.querySelector("[data-js='clear-all-btn']");
const themeToggleBtn = document.querySelector("[data-js='theme-toggle-btn']");
const attributeDemoInput = document.querySelector("[data-js='attribute-demo-input']");
const checkAttributeBtn = document.querySelector("[data-js='check-attribute-btn']");
const grandparentBox = document.querySelector("[data-js='grandparent-box']");
const parentBox = document.querySelector("[data-js='parent-box']");
const childBtn = document.querySelector("[data-js='child-btn']");